### PR TITLE
OP-22194-Fixed PipelineControllerSpec UTs & Readded synchronised in s…

### PR DESCRIPTION
**Pull request by aman-agrawal**
**Parent Jira** : https://devopsmx.atlassian.net/browse/OP-22085
**Jira** : https://devopsmx.atlassian.net/browse/OP-22194

**Summary** :
Supporting Change : https://github.com/spinnaker/front50/pull/1172/files
Found no strong reason to revert above change, so undoing the revert.

**Testing** : 
compile success, service starting locally, PipelineControllerSpec - 9/9 UT passed

### CODE REVIEW

**Comment by kirangodishala** [comment]
@aman-agrawal - Why is this PR looks different from the cherry-pick.

**Comment by aman-agrawal** [comment]
> @aman-agrawal - Why does this PR look different from the cherry-pick.

With this PR, we r undoing that revert as well as we are fixing the UTs in PipelineControllerSpec
Added new Test configuration class to support other testclasses as well. Added Fiat related beans to test configuration class to fix the UTs.

**Comment by kirangodishala** [comment]
> > @aman-agrawal - Why does this PR look different from the cherry-pick.
> 
> With this PR, we r undoing that revert as well as we are fixing the UTs in PipelineControllerSpec Added new Test configuration class to support other testclasses as well. Added Fiat related beans to test configuration class to fix the UTs.

Can you include them as separate commits?

**Comment by aman-agrawal** [comment]
> > > @aman-agrawal - Why does this PR look different from the cherry-pick.
> > 
> > 
> > With this PR, we r undoing that revert as well as we are fixing the UTs in PipelineControllerSpec Added new Test configuration class to support other testclasses as well. Added Fiat related beans to test configuration class to fix the UTs.
> 
> Can you include them as separate commits?

done

**Review by kirangodishala — APPROVED** [review]

**Pull request merged**
